name: Build project
on:

  push:
  pull_request:

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - name: Cache Project Settings
        uses: actions/cache@v2
        with:
          path: dangerpath/ProjectSettings
          key: ProjectSettings-${{ matrix.targetPlatform }}
          restore-keys: ProjectSettings-

      - name: Unity - Activate
        uses: game-ci/unity-activate@v2.0.0
               
          
      - name: Unity Build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: dangerpath # Adjust this path according to your project structure

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
