name: Actions 😎

on: [push, pull_request]

jobs:
  build-windows:
    name: Build for Windows ✨
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      #- name: Cache
      #  uses: actions/cache@v3
      #  with:
       #   path: Library
         # key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
        #  restore-keys: |
         #   Library-

      - name: Build project for Windows
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build

  build-macos:
    name: Build for macOS ✨
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

     # - name: Cache
      #  uses: actions/cache@v3
      #  with:
        #  path: Library
        #  key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
       #   restore-keys: |
         #   Library-

      - name: Build project for macOS
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneOSX

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build

  build-linux:
    name: Build for Linux ✨
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

     # - name: Cache
       # uses: actions/cache@v3
        #path: Library
         # key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
         # restore-keys: |
          #  Library-

      - name: Build project for Linux
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneLinux64

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
