name: Actions 😎


on: [push, pull_request]

jobs:
  - name: Build for Windows
    uses: ./.github/workflows/build-windows.yml

  - name: Build for macOS
    uses: ./.github/workflows/build-macos.yml

  - name: Build for Linux
    uses: ./.github/workflows/build-linux.yml
